### ISSUE TITLE
Implement new CommandGenerator

### ISSUE THREAD

**Issue by julianu** [genericworkflownodes/GenericKnimeNodes#87]
I would like to implement a new CommandGenerator, which actually acts in between the CLI and the OpenMS generator, but for Java. It should take some java params (classpath, Xmx,...) and afterwards gives arguments to the Java program to load a generated XML containing the remaining, not java relevant, parameters from the node (to make it easy enough, I would also take the nice CTD schema).

Is it somehow easy possible to implement such a generator, e.g. with an additional plugin? The package com.genericworkflownodes.knime.execution seems not to get exported from the genericworkflownodes plugin, and with some trial and error approach I always got an
`"Execute failed: Could not instantiate executor/generator (ClassNotFoundException): com.genericworkflownodes.knime.execution.impl.LocalToolExecutor/path.to.example.Generator"`
(even when allowing to export the com.genericworkflownodes.knime.execution package to my test plugin and implementing ICommandGenerator by the new Generator).

Sorry if the answer might be very easy, I am new to the plugin development.

**Comment by aiche** [comment]
There are currently two options for this. 
1. You fork the GKN repository, implement the `CommandGenerator` and as soon as it is mature enough you create a merge request to get the command generator back into our GKN repository.
2. We expose the `CommandGenerator` as extension point and you add a new plugin extending the extension point.

While I would prefer the second option, since it is a more general solution, it will take us some time to wrap the current code behind an extension point. So it depends how long you can wait.

**Comment by aiche** [comment]
fyi .. since c273151659b504d67074dfedb47ac111ecf00c5f we have extension points for executors and command generators

**Comment by jpfeuffer** [comment]
Is this still an issue?

**Comment by julianu** [comment]
For me it is all fine now... you can close it.

**Comment by jpfeuffer** [comment]
Thanks! Closed.
