### ISSUE TITLE
No nodes with output-file only

### ISSUE THREAD

**Issue by julianu** [genericworkflownodes/GenericKnimeNodes#90]
Hej,
I saw you just updated something, but after updating my CTDs to the new schema versions, I still have one problem:
A node which has an ITEM of the type "output-file" will not run, as long as there is no "input-file". I have a node generating a file on its call, that's why I need this. As soon, as an "input-file" is added, the node executes, but then I always have to connect a dummy input-file.
The only error I get - also with debug on, logview stays empty - is:
 ERROR   KNIME-Worker-0 NodeName: Execute failed: Index: 0, Size: 0

**Comment by aiche** [comment]
He, 
so far we never considered the scenario with no input file, therefore this bug was not revealed earlier. I have just pushed a branch to feature/fix-no-input-file-scenario (7497f4565ed2a8f7564bc040cddd3e2f37aa9991) with a potential fix. Could you please verify if this solves your problem? 
Cheers

**Comment by julianu** [comment]
It did almost work, I made just one more small change as seen in the pull-request.
Thanks!
